//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Kashilog.Tests.TestData {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestDataCreateScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestDataCreateScripts() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Api.Kashilog.Tests.TestData.TestDataCreateScripts", typeof(TestDataCreateScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   SET IDENTITY_INSERT enterprise.CmnCompany ON
        ///INSERT INTO enterprise.CmnCompany(CompanyId,CompanyName,ZipCode,Country,City,Address,TelephoneNumber,CreatedDateTime,LastUpdatedDateTime,LastUpdatedSign) VALUES(1,N&apos;江崎グリコ株式会社&apos;,N&apos;555-8502&apos;,N&apos;日本&apos;,N&apos;大阪府大阪市&apos;,N&apos;西淀川区歌島四丁目6番5号&apos;,N&apos;0120-917-111&apos;,N&apos;2017/05/13&apos;,N&apos;2017/05/13&apos;,1);
        ///INSERT INTO enterprise.CmnCompany(CompanyId,CompanyName,ZipCode,Country,City,Address,TelephoneNumber,CreatedDateTime,LastUpdatedDateTime,LastUpdatedSign) VALUES(2,N&apos;森永製菓株式会社&apos;,N&apos;108-8403&apos;,N&apos;日本&apos;,N&apos;東 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SetupKashilog {
            get {
                return ResourceManager.GetString("SetupKashilog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DELETE FROM kashi.MstProduct;
        ///DELETE FROM enterprise.CmnCompany;
        ///DELETE FROM kashi.CmnTaste;
        ///DELETE FROM kashi.CmnTexture;
        ///DELETE FROM kashi.MstProductTaste;
        ///DELETE FROM kashi.MstProductTexture;
        ///
        ///DBCC CHECKIDENT(&apos;kashi.MstProduct&apos;, RESEED, 0);
        ///DBCC CHECKIDENT(&apos;enterprise.CmnCompany&apos;, RESEED, 0);
        ///DBCC CHECKIDENT(&apos;kashi.CmnTaste&apos;, RESEED, 0);
        ///DBCC CHECKIDENT(&apos;kashi.CmnTexture&apos;, RESEED, 0);
        ///DBCC CHECKIDENT(&apos;kashi.MstProductTaste&apos;, RESEED, 0);
        ///DBCC CHECKIDENT(&apos;kashi.MstProductTexture&apos;, RESEED, 0);
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TeardownKashilog {
            get {
                return ResourceManager.GetString("TeardownKashilog", resourceCulture);
            }
        }
    }
}
