name: .NET CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379/tcp
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      mssql-kashilog:
        image: ghcr.io/creatiovitae/kashilogdb:2023-12.21
        ports:
          - 1433/tcp
          - 1433:1433
        options: >-
          --health-cmd "/opt/mssql-tools/bin/sqlcmd -U SA -P h0geFuga -Q 'select 1' -b -o /dev/null"
          --health-interval 60s
          --health-timeout 30s
          --health-start-period 20s
          --health-retries 3
      transaction-mail-kashilog:
        image: schickling/mailcatcher:latest
        ports:
          - "1025:1025"
          - "1080:1080"
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Ping transaction-mail-kashilog
      run: |
        for i in {1..5}; do
          if curl --fail http://127.0.0.1:1080; then
            break
          fi
          echo "transaction-mail-server is not responding, retrying..."
          sleep 5
          if [ $i -eq 5 ]; then
            echo "transaction-mail-server failed to respond after 5 retries"
            exit 1
          fi
        done
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      env:
        TEST_ENVIRONMENT: Ci
